### PR TITLE
Recover CONTRIBUTING.md, Merge FINOS Governance and Move CONTRIBUTING.md to Root

### PR DESCRIPTION
**Pull request by mcleo-d**
## Description

This pull request recovers the Alloy `CONTRIBUTING.md` and applies FINOS Governance updates into existing text. This is done through the following actions and commits ...

- Recover `.github/CONTRIBUTING.md` from commit 0f8c5c74b26b2b93efee91f3ac1988e4538e90bf
- Merge FINOS governance `https://github.com/finos/community/blob/master/governance/Software-Projects/CONTRIBUTING.template.md` into existing `.github/CONTRIBUTING.md` d74b14f
- Delete `CONTRIBUTING.md` from project `root` 828c570
- Move `.github/CONTRIBUTING.md` to project `root` 47d74ba

### CODE REVIEW

**Review by maoo — APPROVED** [review]
LGTM!

**Comment by brooklynrob** [comment]
I can't see the "old" .github/CONTRIBUTING.md -- we're sure the previous CONTRIBUTING.md is going to come back?

**Comment by gs-bracej** [comment]
Sorry for my confusion - please could you confirm which CONTRIBUTING.md we should be using in the code repos, and should it be in .github or root? We're pushing more code today.

**Comment by mcleo-d** [comment]
This PR has been resolved with the acceptance of #245

**Comment by mcleo-d** [comment]
Hi @gs-bracej 

We've just recovered https://github.com/finos/alloy/blob/master/.github/CONTRIBUTING.md as #245 so the content created by the team, including the commit history, is restored. 

Both me and @aitana16 are updating the content of `.github/CONTRIBUTING.md` before a decision led by @brooklynrob is made to move the file into the project `root`.

I hope this helps.

James.

**Comment by gs-bracej** [comment]
Perfect, thanks. We’ll continue pushing code with the original file, if you have an updated version feel free to let us know or just PR it.

**Comment by mcleo-d** [comment]
> Perfect, thanks. We’ll continue pushing code with the original file, if you have an updated version feel free to let us know or just PR it.

@gs-bracej - There will be an update made in the near future, so feel free to add an absolute link to the CONTRIBUTING.md file below to remove the need to update in multiple places when the content changes.

```
[CONTRIBUTING.md](https://github.com/finos/alloy/blob/master/.github/CONTRIBUTING.md)
```

**Pull request closed without merging**
